version: '2'

services:
    nginx:
        image: gcr.io/test-teleprecense/kompose-nginx
        ports:
            - "80:80"
        links:
            - php
    db:
        image: gcr.io/test-teleprecense/kompose-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: api
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: api_dev
    fpm:
        image: gcr.io/test-teleprecense/kompose-fpm
        ports:
            - "9000:9000"
        links:
            - db
        environment:
            - PHP_POOL_LISTEN_HOST=0.0.0.0
            - PHP_CONF_DISPLAY_ERRORS=on 
            - PHP_CONF_ERROR_REPORTING=1
