version: '2'

services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        image: gcr.io/test-teleprecense/kompose-nginx
        ports:
            - "8080:80"
    db:
        build:
            context: ./
            dockerfile: docker/db/Dockerfile
        image: gcr.io/test-teleprecense/kompose-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: api
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: api_dev
    fpm:
        build:
            context: ./
            dockerfile: docker/fpm/Dockerfile
        image: gcr.io/test-teleprecense/kompose-fpm
        volumes:
            - ./api:/source
        working_dir: /source
        ports:
            - "9000:9000"
        environment:
            - PHP_POOL_LISTEN_HOST=0.0.0.0
            - PHP_CONF_DISPLAY_ERRORS=on 
            - PHP_CONF_ERROR_REPORTING=1
